"""
Generate Hydrology Report Skill

Creates a markdown report with discharge calculations, risk analysis,
and plain English explanations for each river.

Returns:
    dict with:
    - success: True/False
    - report_path: Path to generated report (if successful)
    - error: Error message (if failed)
"""

from pathlib import Path
from datetime import datetime


def get_flow_explanation(condition, discharge):
    """
    Generate a 2-sentence plain English explanation of the flow condition.
    """
    if condition == "Low":
        return (f"The river is experiencing low flow conditions with a discharge of {discharge} m³/s. "
                f"This indicates minimal water movement, which is typical during dry periods or upstream water retention.")
    elif condition == "Moderate":
        return (f"The river is flowing at a moderate rate with a discharge of {discharge} m³/s. "
                f"This represents normal flow conditions, suitable for typical river operations and ecosystem health.")
    else:  # High
        return (f"The river is experiencing high flow conditions with a discharge of {discharge} m³/s. "
                f"This elevated flow may indicate recent rainfall, snowmelt, or upstream releases, requiring increased monitoring.")


def run(results=None, df=None, output_file=None, plan=None, **kwargs):
    """
    Generate markdown hydrology report.

    Args:
        results: List of dicts with River, Discharge, Condition, Risk
        df: Optional DataFrame with original data
        output_file: Path to output report file
        plan: Optional dict with plan information
        **kwargs: Additional arguments (ignored)

    Returns:
        dict with success status and report path or error
    """
    result = {
        'success': False,
        'report_path': None,
        'error': None,
        'skill': 'generate_hydrology_report',
        'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    
    try:
        # Validate input
        if not results:
            result['error'] = 'No results provided'
            print("❌ Error: No results to generate report from")
            return result
        
        if not output_file:
            result['error'] = 'No output_file provided'
            print("❌ Error: No output_file provided")
            return result
        
        # Ensure output directory exists
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Generate timestamp
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Write report
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# 🌊 Hydrology Report\n\n")
            f.write(f"*Generated by Hydrology FTE Agent*\n\n")
            f.write(f"**Report Generated:** {timestamp}\n\n")
            
            # Add plan reference if available
            if plan:
                f.write(f"**Reasoning Plan:** [{Path(plan.get('plan_path', '')).name}]({plan.get('plan_path', '')})\n\n")
                f.write(f"**Planning Note:** This report was generated following an AI-created reasoning plan that assessed risks and defined analysis steps.\n\n")
            
            f.write("---\n\n")
            
            for r in results:
                f.write(f"## River: {r['River']}\n\n")
                
                # Find original data for formula calculation
                width = depth = velocity = None
                if df is not None:
                    row = df[df['River'] == r['River']]
                    if not row.empty:
                        width = row['Width_m'].values[0]
                        depth = row['Depth_m'].values[0]
                        velocity = row['Velocity_mps'].values[0]
                
                # Show formula with real numbers
                f.write("### Discharge Calculation\n\n")
                f.write("**Formula:** Q = Width × Depth × Velocity\n\n")
                
                if all(v is not None for v in [width, depth, velocity]):
                    calculated_q = width * depth * velocity
                    f.write(f"**Calculation:** Q = {width}m × {depth}m × {velocity}m/s = **{calculated_q:.1f} m³/s**\n\n")
                else:
                    f.write(f"**Calculated Discharge:** **{r['Discharge']:.1f} m³/s**\n\n")
                
                # Analysis section
                f.write("### Analysis\n\n")
                f.write(f"- **Condition:** {r['Condition']}\n")
                f.write(f"- **Risk Level:** {r['Risk']}\n\n")
                
                # Plain English explanation
                f.write("### What This Means\n\n")
                f.write(get_flow_explanation(r['Condition'], f"{r['Discharge']:.1f}") + "\n\n")
                
                # Risk-specific recommendations
                if r['Risk'] == 'High':
                    f.write("### ⚠️ Recommended Actions\n\n")
                    f.write("1. **Increase monitoring frequency** to hourly\n")
                    f.write("2. **Notify downstream stakeholders** of elevated flows\n")
                    f.write("3. **Check weather forecasts** for additional precipitation\n")
                    f.write("4. **Prepare emergency response** if conditions worsen\n\n")
                
                f.write("---\n\n")
            
            # Summary section
            f.write("## Summary\n\n")
            
            high_rivers = [r for r in results if r['Risk'] == 'High']
            medium_rivers = [r for r in results if r['Risk'] == 'Medium']
            low_rivers = [r for r in results if r['Risk'] == 'Low']
            
            f.write(f"- **Total Rivers Monitored:** {len(results)}\n")
            f.write(f"- **High Risk:** {len(high_rivers)} river(s)\n")
            f.write(f"- **Medium Risk:** {len(medium_rivers)} river(s)\n")
            f.write(f"- **Low Risk:** {len(low_rivers)} river(s)\n\n")
            
            if high_rivers:
                f.write("### ⚠️ Immediate Attention Required\n\n")
                for r in high_rivers:
                    f.write(f"- **{r['River']}**: {r['Discharge']:.1f} m³/s ({r['Condition']} flow)\n")
                f.write("\n")
            
            f.write("\n---\n\n")
            f.write("*This report was generated automatically by the Hydrology FTE Agent.*\n")
        
        # Success
        result['success'] = True
        result['report_path'] = str(output_path)
        result['rivers_in_report'] = len(results)
        
        print(f"✅ Report generated: {output_path}")
        return result
        
    except Exception as e:
        result['error'] = str(e)
        print(f"❌ Error generating report: {e}")
        return result
