from pathlib import Path
from datetime import datetime


def get_flow_explanation(condition, discharge):
    """
    Generate a 2-sentence plain English explanation of the flow condition.

    Args:
        condition: Flow condition (Low, Moderate, High)
        discharge: Discharge value in m³/s

    Returns:
        String explanation
    """
    if condition == "Low":
        return (f"The river is experiencing low flow conditions with a discharge of {discharge} m³/s. "
                f"This indicates minimal water movement, which is typical during dry periods or upstream water retention.")
    elif condition == "Moderate":
        return (f"The river is flowing at a moderate rate with a discharge of {discharge} m³/s. "
                f"This represents normal flow conditions, suitable for typical river operations and ecosystem health.")
    else:  # High
        return (f"The river is experiencing high flow conditions with a discharge of {discharge} m³/s. "
                f"This elevated flow may indicate recent rainfall, snowmelt, or upstream releases, requiring increased monitoring.")


def run(results, df=None, output_file="Hydrology-Vault/Done/report.md"):
    """
    Generate markdown hydrology report with formulas, explanations, and timestamp.

    Args:
        results: List of dicts with River, Discharge, Condition, Risk
        df: Optional DataFrame with original data (Width_m, Depth_m, Velocity_mps)
        output_file: Path to output report file

    Returns:
        True if successful, False otherwise
    """
    try:
        # Validate results
        if not results:
            print("Error: No results to generate report from")
            return False

        # Ensure output directory exists
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Generate timestamp
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# 🌊 Hydrology Report\n\n")
            f.write(f"*Generated by Hydrology FTE Agent*\n\n")
            f.write(f"**Report Generated:** {timestamp}\n\n")
            f.write("---\n\n")

            for r in results:
                f.write(f"## River: {r['River']}\n\n")

                # Find original data for formula calculation
                width = depth = velocity = None
                if df is not None:
                    row = df[df['River'] == r['River']]
                    if not row.empty:
                        width = row['Width_m'].values[0]
                        depth = row['Depth_m'].values[0]
                        velocity = row['Velocity_mps'].values[0]

                # Show formula with real numbers
                f.write("### Discharge Calculation\n\n")
                f.write("**Formula:** Q = Width × Depth × Velocity\n\n")

                if width is not None:
                    calculated = width * depth * velocity
                    f.write(f"**Calculation:** Q = {width}m × {depth}m × {velocity}m/s = **{calculated} m³/s**\n\n")
                else:
                    f.write(f"**Result:** Q = **{r['Discharge']} m³/s**\n\n")

                # Condition and Risk
                f.write("### Analysis\n\n")
                f.write(f"- **Condition:** {r['Condition']}\n")
                f.write(f"- **Risk Level:** {r['Risk']}\n\n")

                # Plain English explanation
                f.write("### What This Means\n\n")
                f.write(f"{get_flow_explanation(r['Condition'], r['Discharge'])}\n\n")

                f.write("---\n\n")

            f.write("*Report complete.*\n")

        print(f"✅ Report generated successfully → {output_file}")
        return True

    except PermissionError:
        print(f"Error: Permission denied writing to: {output_file}")
        return False
    except Exception as e:
        print(f"Error generating report: {e}")
        return False